name: Install Intel Fortran
description: Install, cache, and configure environment for the Intel Fortran compiler
runs:
  using: composite
  steps:
    - uses: fortran-lang/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: intel-classic
        version: 2023.1.0
