name: CI
on:
  push:
    branches:
      - main
      - develop*
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
      - develop*
    paths-ignore:
      - '**.md'
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019, windows-2022 ]

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set bin path (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $bindir = "C:\Program Files (x86)\Intel\oneAPI"
          echo "TEST_BINDIR=$bindir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install compilers
        uses: ./

      - name: Test compilers (Windows bash)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          if command -v ifort &> /dev/null
          then
            echo "ifort found"
          else
            echo "ifort not available"
            exit 1
          fi

          ifort test/hw.f90 -o hw
          output=$(./hw '2>&1')
          if [[ "$output" == *"hello world"* ]]
          then
            echo "compile succeeded"
            echo "$output"
          else
            echo "unexpected output: $output"
            exit 1
          fi

      - name: Test compilers (Windows pwsh)
        if: runner.os == 'Windows'
        shell: pwsh
        run: ./test/test.ps1 "${{ env.TEST_BINDIR }}"

      - name: Test compilers (Windows cmd)
        if: runner.os == 'Windows'
        shell: cmd
        run: call "./test/test.bat"